- type: department
  id: Cargo
  name: department-Cargo #imperial department names
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  name: department-Civilian #imperial department names
  description: department-Civilian-description
  color: "#9FED58"
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer 
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  name: department-Command #imperial department names
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster

- type: department
  id: Engineering
  name: department-Engineering #imperial department names
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical #imperial department names
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - Coroner

- type: department
  id: Security
  name: department-Security #imperial department names
  description: department-Security-description
  color: "#DE3A3A"
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden
  - Brigmedic

- type: department
  id: Science
  name: department-Science #imperial department names
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant

- type: department
  id: Specific
  name: department-Specific #imperial department names
  description: department-Specific-description
  color: "#9FED58"
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist

